### ISSUE TITLE
ERROR in IntegralUIModule is not an NgModule

### ISSUE THREAD

**Issue by eliavmaman** [lidorsystems/integralui-web-angular#1]
follow this [link](http://www.lidorsystems.com/support/articles/angular/contextmenu/contextmenu-component.aspx) .
i use angular-cli.
when i add reference in app.module.ts file , to ```import { IntegralUIModule } from 'integralui-web/integralui.module';``` i get this error.
any Idea?

**Comment by Lidor-Systems** [comment]
Can you tell us what is the error message?

 

We have tried this using the Angular quickstart app, and it works. See attached app.module.ts and app.component.ts file for using the ContextMenu component.

 

 

If you have any questions, don't hesitate to contact us.

 

 

Kind regards,

 

The Support Team

 <mailto:support@lidorsystems.com> support@lidorsystems.com

 <http://www.lidorsystems.com> www.lidorsystems.com

 

 

From: Contact [mailto:contact@lidorsystems.com] 
Sent: Monday, February 06, 2017 5:17 PM
To: support@lidorsystems.com
Subject: FW: [lidorsystems/integralui-web] ERROR in IntegralUIModule is not an NgModule (#1)

**Comment by eliavmaman** [comment]
The error I get is the title of that issue
בתאריך יום ב׳, 6 בפבר׳ 2017 ב-18:35 מאת Lidor-Systems <
notifications@github.com>:

**Comment by Lidor-Systems** [comment]
Did you tried with attached files?

 

At first you need to install the IntegralUIModule, following this:

Installation

Install the repository by running

npm install https://github.com/lidorsystems/integralui-web.git

 

Then open your application module and add a reference to IntegralUI module

import { IntegralUIModule } from 'integralui-web/integralui.module';

 

@NgModule({

  imports:      [ IntegralUIModule ],

  declarations: [ AppComponent ],

  bootstrap:    [ AppComponent ]

})

export class AppModule { }

 

 

 

Kind regards,

 

The Support Team

 <mailto:support@lidorsystems.com> support@lidorsystems.com

 <http://www.lidorsystems.com> www.lidorsystems.com

**Comment by eliavmaman** [comment]
exactly like that...

**Comment by eliavmaman** [comment]
Many developers uses Angular-cli, did u try to install it with the actual cli to check if its works?

**Comment by Lidor-Systems** [comment]
No, we have tried it yet. Because of this information (taken from github page of Angular CLI):

Note

This project is very much still a work in progress.

The CLI is now in beta. 

 

 

We will try it right now, and will see whether it works.

 

 

Kind regards,

 

The Support Team

 <mailto:support@lidorsystems.com> support@lidorsystems.com

 <http://www.lidorsystems.com> www.lidorsystems.com

**Comment by Lidor-Systems** [comment]
It seems that IntegralUIModule is not recognized. 

 

In our setup when using SystemJS, we mention that you need to include a reference to the IntegralUI Web package, like this:

 

    map: {

      'integralui-web': 'npm:integralui-web'

    },

    packages: {

      'integralui-web': {

        defaultExtension: 'js'

      }

    }

 

 

Now, in Angular CLI there is a section in JSON file that can reference 3rd party modules(following this guideline <https://github.com/angular/angular-cli/issues/2460> ):

 

{

  "name": "iuiweb-test",

  "version": "0.0.0",

  "license": "MIT",

  "angular-cli": {},

. . .

 

However, in the moment we don't know what format is acceptable for our module. It has to be a way to reference 3rd part modules.

 

 

We will let you know when we have more information. 

 

 

Kind regards,

 

The Support Team

 <mailto:support@lidorsystems.com> support@lidorsystems.com

 <http://www.lidorsystems.com> www.lidorsystems.com

**Comment by eliavmaman** [comment]
10x i'll decently use it

**Comment by Lidor-Systems** [comment]
Hi Eliav,

 

We have found that Angular CLI doesn't recognize the moduleId field in Component settings. The moduleID is used to detect the relative path of CSS styles, if they are not set in the same folder as the component file. For example, we have just tried this on test component:

 

@Component({

                moduleId: module.id,

                selector: 'iui-test',

                template: '<div>This is a Test</div>'

})

export class TestComponent {

 

                constructor(){

                }

}

 

In above code if we remove the moduleId, there is no error. 

 

 

In current version available, IntegralUIModule uses this variable because we wanted to separate the CSS settings from component files in separate folders. So each component has moduleId variable set. If you use the quick start project from Angular website, you will notice that it works, however we presume that the Angilar CLI is not yet updated and moduleId is not recognized.

 

We will solve this and remove the moduleId from use in all components of IntegralUIModule, so that it will work without problems. We plan to include this in next beta release by the end of this month. This release will also include the Grid and TreeGrid components. 

 

For now, try testing our components using the standard Angular quickstart application.

 

 

NOTE   For technical questions, please send your emails directly to support@lidorsystems.com.

 

 

Kind regards,

 

The Support Team

 <mailto:support@lidorsystems.com> support@lidorsystems.com

 <http://www.lidorsystems.com> www.lidorsystems.com

**Comment by Lidor-Systems** [comment]
Hi,

 

A new beta version 0.7.5 <https://github.com/lidorsystems/integralui-web>  is released. This fixes the problem with Angular CLI and now you can load IntegralUIModule with all components. 

Upon installation we noticed that CSS files cannot be found, although with are using current folder syntax ( stylesUrl: ['./css/some-file.css'] ). You can solve this on your side by coping all files from CSS and Resources folder in your app root folder. Follow the installation guidelines from ReadMe file.

After that you can use all components in normal way. 

 

Note   We will work on this and find a solution soon.

 

 

If you have any questions, don't hesitate to contact us.

 

 

Kind regards,

 

The Support Team

 <mailto:support@lidorsystems.com> support@lidorsystems.com

 <http://www.lidorsystems.com> www.lidorsystems.com

**Comment by Lidor-Systems** [comment]
We have solved the problem with relative paths for CSS files when Angular CLI is used. After installation, in angular-cli.json under styles section add this code line:

"../node_modules/integralui-web/integralui.module.css"

**Comment by eliavmaman** [comment]
Wow.. thanks for your dedication ... really appreciated. :)  
Will try that and let u know . 10x guys

**Comment by Lidor-Systems** [comment]
Upon installing the latest version of Angular CLI, we notice that the error is still thrown. Upon detalied investigation, we find out that the IntegralUIModule was not recognized from the minified integralui.module.js file. After we have replaced this file with its source  integralui.module.ts file, it works correctly. We also removed styleUrls from all component source files.

We have already updated the IntegralUI Web project v0.7.524. You only have to install it and set the CSS file reference, like it is described in the installation section.

In our test app, we are using latest versions of:
•	nodejs v6.9.5
•	npm v3.7.2
•	angular cli v1.0.0-beta28.3
•	angular 2.4.7

Your project should compile now without errors.


Note   Sorry for many tryouts on your side, please accept our apologies.

 
Kind regards,
 
The Support Team
support@lidorsystems.com
www.lidorsystems.com

**Comment by Pavans93** [comment]
Hi,
I'm getting the below error when i run the application. Please help me out to resolve this issue.Thanks in advance.

Uncaught TypeError: i0.ɵɵdefineInjectable is not a function
    at integralui.common.service.js:29
    at Object../node_modules/@lidorsystems/integralui-web/bin/integralui/services/integralui.common.service.js (integralui.common.service.js:29)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/@lidorsystems/integralui-web/bin/integralui/components/integralui.core.js (integralui.core.js:16)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/@lidorsystems/integralui-web/bin/integralui/components/integralui.treeview.js (integralui.treeview.js:16)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/pages/process/add-new-extract/add-new-extract.component.ts (main.js:41772)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/pages/process/process.routing.ts (process.module.ts:217)

**Comment by Lidor-Systems** [comment]
We cannot find i0.ɵɵdefineInjectable code in the integralui.common.service.js. Can you tell us how to recreate the issue, or the best would be to create a sample project that shows the error. You can create a sample project on StackBlitz. 

Also please tell us which version of IntegralUI Web you are using?

**NOTE**   This issue is closed. Please post your message by opening a new issue.
