### ISSUE TITLE
tree-item content is not completely displayed

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-web-angular#15]
Hi,
Here are 2 issues: 
1. when there is no vertical scroll bar the tree-item content is not fully display (please refer to below images).

=> no vertical scroll bar
![issue4](https://user-images.githubusercontent.com/1568013/72771530-25512280-3c3c-11ea-9a04-d9e4fa22d110.png)

=> with fixed height and vertical scroll bar displayed and content fully displayed
![issue5](https://user-images.githubusercontent.com/1568013/72771532-271ae600-3c3c-11ea-8916-cdd0888af11a.png)

https://stackblitz.com/edit/integralui-angular-treeview-hover-item-toolbar-2yht14

2. the horizontal scroll bar is displayed wrongly.

would you remember the codes you provide to us to calculate the longest item width for tree-item?
```
<iui-treeview ..... (updateComplete)="treeUpdateComplete()">
```
```
  public calculateLongestItemWidth(treeviewElement: ElementRef, itemContentElements: QueryList<ElementRef>) {
    const treePageRect = this.integralUICommonService.getPageRect(treeviewElement.nativeElement);

    const list = itemContentElements.toArray();
    list.map(elem => {
      const elemPageRect = this.integralUICommonService.getPageRect(elem.nativeElement);
      const elemWidth = elem.nativeElement.offsetWidth + elemPageRect.left - treePageRect.left;

      this.longestItemWidth = Math.max(this.longestItemWidth, elemWidth);
    });
  }
```

=> this is correct as expected
![issue6](https://user-images.githubusercontent.com/1568013/72777727-9a7b2280-3c51-11ea-8fe5-fdb651253f98.png)
=> after I collapse the item, the horizontal scroll bar should be recalculated. but it didn't. I think you should only check the visible item.
![issue7](https://user-images.githubusercontent.com/1568013/72777731-9e0ea980-3c51-11ea-8676-2bf3bc8d102b.png)

3. the tree-item class is different, please make sure the codes are published property.

![issue8](https://user-images.githubusercontent.com/1568013/72778683-956ba280-3c54-11ea-9083-a240933ec57f.png)

=>online sample: https://stackblitz.com/edit/integralui-angular-treeview-hover-item-toolbar-rtsq89
=>my local: 19.4.211
both should have the same version, but the CSS are different :'(

**Comment by Lidor-Systems** [comment]
1. This is a trivial bug, it shouldn't take long to fix it.
2. We need to check why the horizontal scrollbar visibility is not updated on expand/collapse
3. This is not a bug. The 'iui-treeitem-animate' class is attached to the item element only when **allowAnimation** property is set to **true**. We can see that this property is in online samples, please check out whether you have it in your local project.

The version for latest online samples (that is 19.4.211) is the same as the one you are using in your local project. 

Probably there is also a difference it the way classes are attached in StackBlitz and locally, because when we run the QuickStart project, we can only see the class attached but without ng-reflect-ng-class attributes.

**Comment by robinNode** [comment]
> 1. trivial

Hi,
When I can get the latest package with these fixes? thanks

**Comment by MM-RYO** [comment]
> 1. This is a trivial bug, it shouldn't take long to fix it.
> 2. We need to check why the horizontal scrollbar visibility is not updated on expand/collapse
> 3. This is not a bug. The 'iui-treeitem-animate' class is attached to the item element only when **allowAnimation** property is set to **true**. We can see that this property is in online samples, please check out whether you have it in your local project.
> 
> The version for latest online samples (that is 19.4.211) is the same as the one you are using in your local project.
> 
> Probably there is also a difference it the way classes are attached in StackBlitz and locally, because when we run the QuickStart project, we can only see the class attached but without ng-reflect-ng-class attributes.

Hi,
When I can get the latest package with these fixes? thanks

**Comment by Lidor-Systems** [comment]
We will post/send a new update by the end of this week.

**Comment by Lidor-Systems** [comment]
1. This is now fixed. 
Apparently when hover and/or select templates are in use, the item needs to display its background in full (the TreeView width). This requires changes in element width, but because of it Angular change detection alters the size of longest item width during calculation. We added a flag that prevents this behavior, and the longest item width is now correctly calculated.

2. This is fixed. 
We have updated the code that handles the scrolling size and visibility (related to above issue #1). Now it works, whenever an item expand/collapse, the scrollbar visibility is correctly updated.

The update will be available tomorrow.
