### ISSUE TITLE
How to add tooltip for expand/collapse icon？

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-web-angular#19]
![image](https://user-images.githubusercontent.com/1568013/107141432-98baf480-6963-11eb-9f03-f9e8615149cc.png)

**Comment by Lidor-Systems** [comment]
You cannot add a tooltip to the built-in expand box, but you can add your own expand box and customize it. 

Follow these steps:

1. First you need to hide the built-in expand box by setting the showExpandBox property to false
2. Change the item template so that now includes a custom expand box

```
<ng-template let-item>
    <span [ngClass]="getExpandBoxClass(item)" (mousedown)="expandBoxMouseDown($event, item)"></span>
    <span>{{item.text}}</span>
</ng-template>
```

3. Set expand box appearance based on whether the item has children and when it's expanded or collapsed

```
    getExpandBoxClass(item: any){
        let classNames = [];

        classNames.push('iui-treeitem-expand-box');

        if (item.items && item.items.length > 0){
            if (item.expanded !== false)
                classNames.push('iui-treeitem-expand-box-open');
            else
                classNames.push('iui-treeitem-expand-box-close');
        }

        return classNames;
    }

    expandBoxMouseDown(e: any, item: any){
        this.treeview.toggle(item);
    }
```

4. Add the Tooltip directive to the expand box element

```
<ng-template let-item>
    <span [ngClass]="getExpandBoxClass(item)" (mousedown)="expandBoxMouseDown($event, item)" [iuiTooltip]="item.tooltip" [tooltipRef]="tooltipReference"></span>
    <span class="treeview-fsld-item-label">{{item.text}}</span>
</ng-template>
```

5. Tooltip will appear only if title field is set and a reference to the top element, so that it appear on top of any other elements:

```
    @ViewChild('application', {read: ViewContainerRef, static: false}) applicationRef: ViewContainerRef;

    public tooltipReference: any = null;
    
    ngAfterViewInit(){
        // Set the reference component by which the position of tooltip is calculated
        // Usually, the appRef should point to the root component, to avoid position adjustment
        this.tooltipReference = this.applicationRef;

        // Get a flat list of all items in tree hierarchy
        this.treeview.updateFullList();

        let list: Array<any> = this.treeview.getFullList();
        list.map(item => item.tooltip = { title: item.text });
    }
```

**NOTE**   Here you don't need to cycle through all items, if you have already set the tooltip field (or any other custom field which will hold the tooltip title). But the tooltipReference must be set after the component is initilaized.

Now whenever you move the mouse cursor over the item expand box, a tooltip will appear. You can customize the tooltip via settings, check out the Tooltip Overview sample.

You can also add your own tooltip or a 3rd party component in similar way.

**Comment by MM-RYO** [comment]
> 
> 
> You cannot add a tooltip to the built-in expand box, but you can add your own expand box and customize it.
> 
> Follow these steps:
> 
>     1. First you need to hide the built-in expand box by setting the showExpandBox property to false
> 
>     2. Change the item template so that now includes a custom expand box
> 
> 
> ```
> <ng-template let-item>
>     <span [ngClass]="getExpandBoxClass(item)" (mousedown)="expandBoxMouseDown($event, item)"></span>
>     <span>{{item.text}}</span>
> </ng-template>
> ```
> 
>     1. Set expand box appearance based on whether the item has children and when it's expanded or collapsed
> 
> 
> ```
>     getExpandBoxClass(item: any){
>         let classNames = [];
> 
>         classNames.push('iui-treeitem-expand-box');
> 
>         if (item.items && item.items.length > 0){
>             if (item.expanded !== false)
>                 classNames.push('iui-treeitem-expand-box-open');
>             else
>                 classNames.push('iui-treeitem-expand-box-close');
>         }
> 
>         return classNames;
>     }
> 
>     expandBoxMouseDown(e: any, item: any){
>         this.treeview.toggle(item);
>     }
> ```
> 
>     1. Add the Tooltip directive to the expand box element
> 
> 
> ```
> <ng-template let-item>
>     <span [ngClass]="getExpandBoxClass(item)" (mousedown)="expandBoxMouseDown($event, item)" [iuiTooltip]="item.tooltip" [tooltipRef]="tooltipReference"></span>
>     <span class="treeview-fsld-item-label">{{item.text}}</span>
> </ng-template>
> ```
> 
>     1. Tooltip will appear only if title field is set and a reference to the top element, so that it appear on top of any other elements:
> 
> 
> ```
>     @ViewChild('application', {read: ViewContainerRef, static: false}) applicationRef: ViewContainerRef;
> 
>     public tooltipReference: any = null;
>     
>     ngAfterViewInit(){
>         // Set the reference component by which the position of tooltip is calculated
>         // Usually, the appRef should point to the root component, to avoid position adjustment
>         this.tooltipReference = this.applicationRef;
> 
>         // Get a flat list of all items in tree hierarchy
>         this.treeview.updateFullList();
> 
>         let list: Array<any> = this.treeview.getFullList();
>         list.map(item => item.tooltip = { title: item.text });
>     }
> ```
> 
> **NOTE** Here you don't need to cycle through all items, if you have already set the tooltip field (or any other custom field which will hold the tooltip title). But the tooltipReference must be set after the component is initilaized.
> 
> Now whenever you move the mouse cursor over the item expand box, a tooltip will appear. You can customize the tooltip via settings, check out the Tooltip Overview sample.
> 
> You can also add your own tooltip or a 3rd party component in similar way.

Hi,
Can we have an API/property for this in feature release? thanks

**Comment by Lidor-Systems** [comment]
This is outside of the TreeView, the Tooltip is a separate component. You can modify the appearance of the built-in expand box, but you cannot add tooltips or any other popup components to it.

Can you tell us why do you need a tooltip over the expand box?

**Comment by MM-RYO** [comment]
> Can you tell us why do you need a tooltip over the expand box

we want to show a hint on the expand box to let user know the usage of expanding.
e.g. : if click the expand only the children nodes will be loaded
        if press Ctrl + click all sub-level descendants will be loaded.

**Comment by Lidor-Systems** [comment]
Its possible to add this feature. We need to see what is the best way to implement this in code, whether a new property is required or a new field name so you can add a tooltip title on your side. The problem here is that using the Tooltip will add dependency on the TreeView, which we want to avoid. This is the reason using templates is much better, it allows you to add dependencies on demand and keep the code smaller.

However, this will be still generic, using our Tooltip directive where you can only add plain text. For more customization, you will need to use the steps described in this topic above.

**Comment by MM-RYO** [comment]
> 
> 
> Its possible to add this feature. We need to see what is the best way to implement this in code, whether a new property is required or a new field name so you can add a tooltip title on your side. The problem here is that using the Tooltip will add dependency on the TreeView, which we want to avoid. This is the reason using templates is much better, it allows you to add dependencies on demand and keep the code smaller.
> 
> However, this will be still generic, using our Tooltip directive where you can only add plain text. For more customization, you will need to use the steps described in this topic above.

ok. thanks
