### ISSUE TITLE
The root button of breadcrumb doesn't work when the viewport is resized

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-web-angular#20]
The full breadcrumb is 
LIbraries ->Documents -> My Documents -> Publish Documents -> Computer -> Storage (D:)

Sample:
https://stackblitz.com/edit/integralui-breadcrumb-overview-apdg6s?file=src%2Fapp%2Fapp.component.ts

![image](https://user-images.githubusercontent.com/1568013/107478938-45d87b80-6bb5-11eb-9995-c65c8930089d.png)

If you manually to select item the root button will be displayed as expected
![image](https://user-images.githubusercontent.com/1568013/107479174-b54e6b00-6bb5-11eb-9d19-b5b1efba1117.png)

**Comment by Lidor-Systems** [comment]
In this sample project set the correct path for the root button image:

```
.iui-breadcrumb-root-button-box
{
    background: url(https://www.lidorsystems.com/images/integralui-web/icons/menu-button.ico);
}
```

**Comment by MM-RYO** [comment]
> .iui-breadcrumb-root-button-box
> {
>     background: url(https://www.lidorsystems.com/images/integralui-web/icons/menu-button.ico);
> }

No. this is not the root cause. you can try to drag&drop the splitter bar between 'Preview' and 'Code' window. 
the breadcrumb couldn't refresh the layout correctly.

![image](https://user-images.githubusercontent.com/1568013/108439328-059b8c00-728c-11eb-8db0-f6e594b3fd2c.png)

**Comment by Lidor-Systems** [comment]
We are not sure why the breadcrumb layout is not updated when its size changes, because the change detection code is present when size changes.


You can solve this on your side by using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver). This new API tracks changes to dimensions of specific element. Follow these steps:

1. In HTML added variable to the Breadcrumb component

`<iui-breadcrumb [items]="items" . . . #breadcrumb>`

2. Get a reference to the Breadcrumb component using that variable

```
import { IntegralUIBreadCrumb } from "./integralui/components/integralui.breadcrumb";

. . .

@ViewChild("breadcrumb") breadcrumb: IntegralUIBreadCrumb;
```

3. Add these variables:

```
// Set a variable that will have a reference to the ResizeObserver for the Breadcrumb element
private breadcrumbObserver = null;
// A variable to the Breadcrumb element
private breadcrumbElem = null;
// Store the breadcrumb width, use this to update the Breadcrumb only when its size changes
public breadcrumbWidth = 0;
```

4. In component constructor set the ResizeObserver. If there are changes to the breadcrumb width, update its layout.

```
constructor(){
    this.breadcrumbObserver = new ResizeObserver(entries => {
        if (entries && entries.length > 0 && entries[0].contentRect) {
            if (this.breadcrumbWidth !== entries[0].contentRect.width) {
                this.breadcrumbWidth = entries[0].contentRect.width;
                this.breadcrumb.updateLayout();
            }
        }
    });
}
```

5. Start observing changes when component is initialized and make sure the observer is closed before component is destroyed:

```
ngAfterViewInit() {
    // Use a class or any other standard CSS selector to locate the breadcrumb. 
    // This doesn't work with ViewChild and ElementRef, so you need to use it in regular way
    this.breadcrumbElem = document.querySelector(".iui-breadcrumb");

    if (this.breadcrumbObserver)
        this.breadcrumbObserver.observe(this.breadcrumbElem);
}

ngOnDestroy() {
    if (this.breadcrumbObserver) 
        this.breadcrumbObserver.disconnect();

    this.breadcrumbObserver = null;
}
```

6. Add a handler to window resize event. Strange the above code should work without this, but in StackBlitz we noticed that the component is not refreshed when layout is updated. By handling window resize, its refreshed. This handler doesn't require any code inside.

```
@HostListener("window:resize", ["$event"])
  onWindowResize(e: any) {}
```

That's it, now whenever the breadrumb width changes, it is also updated. The root button should now appear.
