### ISSUE TITLE
Tree nodes are gone except root node when deleting selected items

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-web-angular#22]
Here is the demo
https://stackblitz.com/edit/integralui-treeview-overview-kft8fe

Steps:
1. click 'select items' button to select last 7 items.
2. click 'scroll to' button to navigate to the last item.
3. click 'delete' button to delete selected items

I think the problem could be in: 
this.treeview.suspendLayout();
this.treeview.resumeLayout();
this.treeview.updateLayout();

![image](https://user-images.githubusercontent.com/1568013/110091712-b600a880-7dd3-11eb-856a-3857c47a6566.png)

![image](https://user-images.githubusercontent.com/1568013/110091607-979aad00-7dd3-11eb-83d1-971f0798b39b.png)

**Comment by Lidor-Systems** [comment]
We have found the cause of this problem and now is fixed.

Apparently, because of virtualization the calculation of visible range for items created in the DOM was incorrect. When scroll position is at max value and then removing items, causes problem with updating on how much items can be presented in the current view. This doesn't happen always, in most cases appears when scrollbar becomes hidden, during removal.

Anyway, this is now fixes. The fix will be included in coming update v21.1, scheduled for release on 16 Mar 2021.

**Comment by MM-RYO** [comment]
Hi,
Can we have an urgent fixing for both issues (21 & 22)? 
we will have an alpha-release on 10/3/2021, the feature is important to us. 

thanks

**Comment by Lidor-Systems** [comment]
Yes, you can download this update from here:
[IntegralUI Web - TreeView v20.3.374 - HOT FIX](https://www.lidorsystems.com/downloads/integralui/hot-fixes/tmp/iui-web-treeview-203374-gTx9.zip)

Extract the content of the zip file and copy/paste the files in your project referencing folder at corresponding directory: /integralui/components.
